name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.TENSORFLOWLITE_BUILD_DEPLOY_KEY_FULL_ACCESS }}

      - name: Get TensorFlow versions
        run: |
          CURRENT_TENSORFLOW_VERSION=$(cat TENSORFLOW_VERSION)
          echo CURRENT_TENSORFLOW_VERSION=$CURRENT_TENSORFLOW_VERSION >> $GITHUB_ENV
          echo "Current TensorFlow Version : $CURRENT_TENSORFLOW_VERSION"

          LATEST_TENSORFLOW_VERSION=$(curl -sL https://api.github.com/repos/tensorflow/tensorflow/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo LATEST_TENSORFLOW_VERSION=$LATEST_TENSORFLOW_VERSION >> $GITHUB_ENV
          echo "Latest TensorFlow Version  : $LATEST_TENSORFLOW_VERSION"

      - name: Update TensorFlow
        if: env.LATEST_TENSORFLOW_VERSION != env.CURRENT_TENSORFLOW_VERSION
        run: |
          echo $LATEST_TENSORFLOW_VERSION > TENSORFLOW_VERSION
          git submodule update --init --depth=1 tensorflow
          cd tensorflow
          git fetch origin tag v$LATEST_TENSORFLOW_VERSION
          git checkout v$LATEST_TENSORFLOW_VERSION

      - name: Commit & push
        if: env.LATEST_TENSORFLOW_VERSION != env.CURRENT_TENSORFLOW_VERSION
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am v$LATEST_TENSORFLOW_VERSION
          git tag v$LATEST_TENSORFLOW_VERSION
          git push origin : v$LATEST_TENSORFLOW_VERSION
